export const AVAILABLE_PROFILES = [
  { developer: "Alibaba", model: "Qwen 3 235B", slug: "qwen-3-235b-a22b", plan: "All" },
  { developer: "Alibaba", model: "Qwen 3 235B (reasoning)", slug: "qwen-3-235b-a22b-thinking", plan: "All" },
  { developer: "Alibaba", model: "Qwen 3 Coder", slug: "qwen-3-coder", plan: "All" },
  { developer: "Anthropic", model: "Claude 4.5 Haiku", slug: "claude-4-haiku", plan: "Ultimate" },
  { developer: "Anthropic", model: "Claude 4.5 Sonnet", slug: "claude-4-sonnet", plan: "Ultimate" },
  { developer: "Anthropic", model: "Claude 4.5 Opus", slug: "claude-4-opus", plan: "Ultimate" },
  { developer: "Anthropic", model: "Claude 4.5 Sonnet (Reasoning)", slug: "claude-4-sonnet-thinking", plan: "Ultimate" },
  { developer: "Anthropic", model: "Claude 4.5 Opus (Reasoning)", slug: "claude-4-opus-thinking", plan: "Ultimate" },
  { developer: "Anthropic", model: "Claude 4.5 Haiku (Reasoning)", slug: "claude-4-haiku-thinking", plan: "Ultimate" },
  { developer: "Deepseek", model: "DeepSeek Chat V3.1 Terminus", slug: "deepseek", plan: "All" },
  { developer: "Google", model: "Gemini 3 Flash", slug: "gemini-3-flash", plan: "All" },
  { developer: "Google", model: "Gemini 3 Flash (reasoning)", slug: "gemini-3-flash-thinking", plan: "All" },
  { developer: "Google", model: "Gemini 2.5 Flash", slug: "gemini-2-5-flash", plan: "All" },
  { developer: "Google", model: "Gemini 2.5 Flash Lite", slug: "gemini-2-5-flash-lite", plan: "All" },
  { developer: "Google", model: "Gemini 2.5 Pro", slug: "gemini-2-5-pro", plan: "Ultimate" },
  { developer: "Google", model: "Gemini 3 Pro", slug: "gemini-3-pro", plan: "Ultimate" },
  { developer: "Meta", model: "Llama 4 Maverick", slug: "llama-4-maverick", plan: "All" },
  { developer: "Mistral AI", model: "Mistral Small", slug: "mistral-small", plan: "All" },
  { developer: "Mistral AI", model: "Mistral Medium", slug: "mistral-medium", plan: "All" },
  { developer: "Moonshot AI", model: "Kimi K2", slug: "kimi-k2", plan: "All" },
  { developer: "Moonshot AI", model: "Kimi K2 (reasoning) (preview)", slug: "kimi-k2-thinking", plan: "All" },
  { developer: "Nous Research", model: "Hermes-4-405B (reasoning)", slug: "hermes-4-405b-thinking", plan: "All" },
  { developer: "OpenAI", model: "GPT 5 Mini", slug: "gpt-5-mini", plan: "All" },
  { developer: "OpenAI", model: "GPT 5 Nano", slug: "gpt-5-nano", plan: "All" },
  { developer: "OpenAI", model: "GPT OSS 120B", slug: "gpt-oss-120b", plan: "All" },
  { developer: "OpenAI", model: "GPT 5.1", slug: "gpt-5.1", plan: "Ultimate" },
  { developer: "OpenAI", model: "GPT 5.1 Codex", slug: "gpt-5.1-codex", plan: "Ultimate" },
  { developer: "OpenAI", model: "o3 pro", slug: "o3-pro", plan: "Ultimate" },
  { developer: "OpenAI", model: "ChatGPT", slug: "chatgpt-4o", plan: "Ultimate" },
  { developer: "xAI", model: "Grok 4 Fast", slug: "grok-4-fast", plan: "All" },
  { developer: "xAI", model: "Grok 4 Fast (Reasoning)", slug: "grok-4-fast-thinking", plan: "All" },
  { developer: "xAI", model: "Grok 4", slug: "grok-4", plan: "Ultimate" },
  { developer: "Z.ai", model: "GLM-4.6 (preview)", slug: "glm-4-6", plan: "All" },
  { developer: "Z.ai", model: "GLM-4.6 (reasoning) (preview)", slug: "glm-4-6-thinking", plan: "All" }
];
